[package]
name = "psd"
version = "0.1.0"
authors = ["Chinedu Francis Nwafili <frankie.nwafili@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1.5"

[workspace]
members = [
    "examples/drag-drop-browser"
]

[profile.release]
lto = true
